### ISSUE TITLE
Cannot configure Starbuncle to take from chests

### ISSUE THREAD

**Issue by Ashendale** [baileyholl/Ars-Nouveau#1096]
Ars version 4.3.0
Minecraft 1.20.1
Forge 47.1.44

Title. Since I updated to said version, I can link Starbuncles to deposit on inventories, but I cannot have them take them from any. Those that were configured with the previous version retain their configuration and functionality. If I reset them, I can no longer have them take from inventories.

Tested with regular chests and Storage Drawers Controller blocks. Tested with older and freshly spawned Starbuncles. Tried clearing all configurations and reset them, still didn't work.

**Comment by Alexthw46** [comment]
Messed up a thing with #1067 and should be fixed with #1074

**Comment by Ashendale** [comment]
I'm a bit dumb on figuring when those things are implemented or not, but the issue is still present on version 4.4.0.
