### ISSUE TITLE
Breaking A Scribes Table Crashed The Game

### ISSUE THREAD

**Issue by KamikazePigeon** [baileyholl/Ars-Nouveau#170]
Not sure what caused it, but when I placed and broke a Scribe's Table, the entire game crashed. It might be worth noting that it was a LAN server hosted by someone else (not me) and I was the one who broke the table. Both our games crashed and we got the same crash report.

[crash-2021-02-02_08.51.14-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5915085/crash-2021-02-02_08.51.14-client.txt)

**Comment by baileyholl** [comment]
Hello,
This is a known bug with Optifine, they will have to fix this.

**Comment by sandalle** [comment]
May not be just OptiFine as I'm _not_ using OptiFine and just got the same crash on ars_nouveau-1.16.4-1.11.4 with a dedicated server separate from the client : [crash-2021-02-07_19.41.23-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5941198/crash-2021-02-07_19.41.23-client.txt)

Client crashed, but server and other players on the server continued to play without issue.

**Comment by baileyholl** [comment]
Are you able to reproduce this without Ferritecore @sandalle? I have added an extra check, but I cannot reproduce this in a simple forge environment.

**Comment by sandalle** [comment]
@baileyholl without ferritecore-1.1.1.jar, I still get this crash, but with a slightly different error, when breaking the Scribes Table on Forge 1.16.5-36.0.15: [crash-2021-02-10_10.47.32-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5960691/crash-2021-02-10_10.47.32-client.txt) (this one was tested in a single player world, not the dedicated server from my earlier report).

I'll see if I can narrow down which mod(s) are causing a conflict.

**Comment by sandalle** [comment]
Nope, still get the crash with just Ars Nouveou (and required libs) installed @baileyholl : [crash-2021-02-10_14.16.50-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5961881/crash-2021-02-10_14.16.50-client.txt)

I'll try updating Forge next as I see some TileEntity fixes in http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.21/forge-1.16.5-36.0.21-changelog.txt .

**Comment by sandalle** [comment]
It doesn't seem to be related to this forge-client.toml settings I changed from default (false) either, as putting it back to false I still crash:
```
	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = true
```

This setting is "required" (more recommended with a nag message if you don't) by Refined Storage (see release notes in https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3091433 ) for MC 1.16+, and possibly other mods make use of the improved lighting pipeline.

**Comment by baileyholl** [comment]
hmm, must be something changed in forge then. I have released the extra checks here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3202644 

Hopefully that should fix it.

**Comment by sandalle** [comment]
Still crashed with Forge 1.16.5-36.0.21 and ars_nouveau-1.16.4-1.11.5 : [crash-2021-02-13_16.18.03-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5976757/crash-2021-02-13_16.18.03-client.txt) . I'll try again later with _just_ Ars Nouveu and dependencies installed.

**Comment by baileyholl** [comment]
Hmm, that log doesn't mention ars nouveau this time, could it be another mod now?
